[env]
build_flags = -Werror=switch
lib_deps = bblanchon/ArduinoJson@^7.4.3

[env:native]
platform = native
test_framework = googletest

[env:esp32]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
lib_deps =
    ${env.lib_deps}
    links2004/WebSockets@^2.7.3
    tamctec/TAMC_GT911@1.0.2